### ISSUE TITLE
Flyway exceptions in db-init container

### ISSUE THREAD

**Issue by msnwatson** [department-of-veterans-affairs/abd-vro#1558]
There are two exceptions that emerged on 05/10/23 during deployment within the db-init container related to Flyway. They are copied in their entirety below.

**Acceptance Criteria**

1. The exceptions below are not produced during a deployment as the db-init container is executed in any environment. 

**Not included in this work**

A note about things that should not be considered necessary.

**Notes about work**

Exception 1: 
```
ERROR: Unable to create JSON report
org.flywaydb.core.api.FlywayException: Unable to write JSON to file: report.json (Permission denied)
	at org.flywaydb.core.internal.util.JsonUtils.jsonToFile(JsonUtils.java:46)
	at org.flywaydb.commandline.utils.OperationsReportUtils.createJsonReport(OperationsReportUtils.java:58)
	at org.flywaydb.commandline.Main.main(Main.java:178)
```

Exception 2:
```
ERROR: Unable to create HTML report
org.flywaydb.core.api.FlywayException: Unable to write HTML to file: report.html (Permission denied)
	at org.flywaydb.core.internal.util.HtmlUtils.toHtmlFile(HtmlUtils.java:36)
	at org.flywaydb.commandline.utils.OperationsReportUtils.createHtmlReport(OperationsReportUtils.java:49)
	at org.flywaydb.commandline.Main.main(Main.java:179)
```

**Comment by dianagriffin** [comment]
Closing as out of date
