### ISSUE TITLE
"Listener threw exception" error when passing valid JSON

### ISSUE THREAD

**Issue by engineer-plus-plus** [department-of-veterans-affairs/abd-vro#1737]
Having started svc-xample-j (the service) using
```
docker kill $(docker ps -q)
docker rm $(docker ps -a -q)
COMPOSE_PROFILES="all" gradle :dockerComposeDown

source scripts/setenv.sh
./gradlew :dockerComposeUp
./gradlew :domain-xample:dockerComposeUp
```
having manually restarted of RMQ,

And having published valid JSON:

```
{"resourceId":"b",
"diagnosticCode":"a",
"statusMessage":"sm",
"status":"statusss"}
```

 to the the que leading to the service, following error appears in the logs. 

```
org.springframework.amqp.rabbit.support.ListenerExecutionFailedException: Listener threw exception
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.wrapToListenerExecutionFailedExceptionIfNeeded(AbstractMessageListenerContainer.java:1788) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1678) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1593) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1581) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1572) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1516) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:1001) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:948) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:86) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1326) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1232) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: org.springframework.amqp.rabbit.listener.adapter.ReplyFailureException: Failed to send reply with payload 'InvocationResult [returnValue=SomeDtoModel(resourceId=b, diagnosticCode=a, status=statusss, statusCode=417, statusMessage=java.lang.NumberFormatException: For input string: "b"), returnType=class gov.va.vro.model.xample.SomeDtoModel, bean=gov.va.vro.services.xample.XampleJavaMicroservice@77f83fcd, method=public gov.va.vro.model.xample.SomeDtoModel gov.va.vro.services.xample.XampleJavaMicroservice.receiveMessage(gov.va.vro.model.xample.SomeDtoModel)]'
	at org.springframework.amqp.rabbit.listener.adapter.AbstractAdaptableMessageListener.doHandleResult(AbstractAdaptableMessageListener.java:492) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	at org.springframework.amqp.rabbit.listener.adapter.AbstractAdaptableMessageListener.handleResult(AbstractAdaptableMessageListener.java:416) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandlerAndProcessResult(MessagingMessageListenerAdapter.java:211) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:148) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1674) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	... 10 common frames omitted
Caused by: org.springframework.amqp.AmqpException: Cannot determine ReplyTo message property value: Request message does not contain reply-to property, and no default response Exchange was set.
	at org.springframework.amqp.rabbit.listener.adapter.AbstractAdaptableMessageListener.getReplyToAddress(AbstractAdaptableMessageListener.java:592) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	at org.springframework.amqp.rabbit.listener.adapter.AbstractAdaptableMessageListener.doHandleResult(AbstractAdaptableMessageListener.java:488) ~[spring-rabbit-2.4.12.jar!/:2.4.12]
	... 14 common frames omitted
```

**Comment by engineer-plus-plus** [comment]
Having removed the counterproductive `try/catch` that masked the true error and having arrived to this code:

```
  public SomeDtoModel receiveMessage(SomeDtoModel model)  throws InterruptedException{
    log.info("Received: " + model);
    Thread.sleep(1000);
    
    return model;
  }
  ```
  We can observe that the true exception is this:
  ```
  Caused by: org.springframework.amqp.rabbit.listener.adapter.ReplyFailureException: Failed to send reply with payload 'InvocationResult [returnValue=SomeDtoModel(resourceId=1, diagnosticCode=2, status=DONE, statusCode=200, statusMessage=sm), returnType=class gov.va.vro.model.xample.SomeDtoModel, bean=gov.va.vro.services.xample.XampleJavaMicroservice@18e87bb3, method=public gov.va.vro.model.xample.SomeDtoModel gov.va.vro.services.xample.XampleJavaMicroservice.receiveMessage(gov.va.vro.model.xample.SomeDtoModel)]'
  ```

**Comment by yoomlam** [comment]
To manually test `svc-xample-j`:
Start up:
```
source scripts/setenv.sh
./gradlew :dockerComposeUp
./gradlew :domain-xample:dockerComposeUp
COMPOSE_PROFILES="" ./gradlew :app:dockerComposeUp
```

Open a browser to http://localhost:8110/swagger and go to the POST `​/v3​/xample-resource` section and open it. Click "Try it out". In the *Request body*, replace `null` with:
```
{
"resourceId":"123",
"diagnosticCode":"J"
}
```
Note: `diagnosticCode` must be `J` in order for the request to be routed to the `svc-xample-j` microservice, as coded in [Xample's Camel route](https://github.com/department-of-veterans-affairs/abd-vro/blob/0cafef12934b119996d9c0bad1a9e9b9363c6ffb/domain-xample/xample-workflows/src/main/java/gov/va/vro/routes/xample/XampleRoutes.java#L130-L131).

Click Execute. The response code should be 201 with response body:
```
{
  "resourceId": "123",
  "diagnosticCode": "J",
  "status": "PROCESSING",
  "statusCode": 0
}
```

The above can also be done with `curl`.

Check the logs:
```
❯ docker logs vro-xample-workflows-1
Setting environment variables from VRO_SECRETS_*
Running xample-workflows-3.1.1-SNAPSHOT.jar; health check port: 10021

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.7.12)

2023-06-27 14:38:15.720  INFO 1 --- [           main] g.v.v.r.x.XampleWorkflowsApplication     : Starting XampleWorkflowsApplication using Java 17.0.7 on 12c11a87d9e1 with PID 1 (/app/fat.jar started by tron in /app)
2023-06-27 14:38:15.778  INFO 1 --- [           main] g.v.v.r.x.XampleWorkflowsApplication     : No active profile set, falling back to 1 default profile: "default"
2023-06-27 14:38:21.909  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2023-06-27 14:38:22.416  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 467 ms. Found 7 JPA repository interfaces.
2023-06-27 14:38:29.501  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2023-06-27 14:38:29.559  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-06-27 14:38:29.560  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.75]
2023-06-27 14:38:29.874  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-06-27 14:38:29.874  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 13578 ms
2023-06-27 14:38:31.968  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2023-06-27 14:38:32.616  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.6.15.Final
2023-06-27 14:38:33.460  INFO 1 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2023-06-27 14:38:34.019  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2023-06-27 14:38:34.835  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2023-06-27 14:38:34.992  INFO 1 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL10Dialect
2023-06-27 14:38:39.956  INFO 1 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2023-06-27 14:38:40.010  INFO 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2023-06-27 14:38:45.994  INFO 1 --- [           main] g.v.vro.camel.MessageQueueConfiguration  : rabbitmq ConnectionFactory: connecting to rabbitmq-service:5672
2023-06-27 14:38:46.954  WARN 1 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2023-06-27 14:38:49.699  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2023-06-27 14:38:51.365  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 10021 (http)
2023-06-27 14:38:51.377  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-06-27 14:38:51.378  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.75]
2023-06-27 14:38:51.391  INFO 1 --- [           main] o.a.c.c.C.[Tomcat-1].[localhost].[/]     : Initializing Spring embedded WebApplicationContext
2023-06-27 14:38:51.392  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1641 ms
2023-06-27 14:38:51.482  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2023-06-27 14:38:51.719  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 10021 (http) with context path ''
2023-06-27 14:38:53.005  INFO 1 --- [           main] o.a.c.c.rabbitmq.RabbitMQComponent       : Auto-detected single instance: rabbitmqConnectionFactory of type ConnectionFactory in Registry to be used as ConnectionFactory when creating endpoint: rabbitmq://v3?queue=postResource&routingKey=postResource
2023-06-27 14:38:53.128  INFO 1 --- [           main] o.a.c.c.rabbitmq.RabbitMQComponent       : Auto-detected single instance: rabbitmqConnectionFactory of type ConnectionFactory in Registry to be used as ConnectionFactory when creating endpoint: rabbitmq://xample?routingKey=serviceJ&skipQueueBind=true
2023-06-27 14:38:53.283  INFO 1 --- [           main] o.a.c.impl.engine.AbstractCamelContext   : Apache Camel 3.19.0 (camel-1) is starting
2023-06-27 14:38:53.861  INFO 1 --- [           main] c.s.b.CamelSpringBootApplicationListener : Starting CamelMainRunController to ensure the main thread keeps running
2023-06-27 14:38:53.863  INFO 1 --- [inRunController] org.apache.camel.main.MainSupport        : Apache Camel (Main) 3.19.0 is starting
2023-06-27 14:38:53.936  INFO 1 --- [           main] o.a.c.impl.engine.AbstractCamelContext   : Routes startup (started:5)
2023-06-27 14:38:53.936  INFO 1 --- [           main] o.a.c.impl.engine.AbstractCamelContext   :     Started route1 (direct://saveToDb)
2023-06-27 14:38:53.936  INFO 1 --- [           main] o.a.c.impl.engine.AbstractCamelContext   :     Started postXResource-route (rabbitmq://v3)
2023-06-27 14:38:53.936  INFO 1 --- [           main] o.a.c.impl.engine.AbstractCamelContext   :     Started route2 (direct://serviceA)
2023-06-27 14:38:53.937  INFO 1 --- [           main] o.a.c.impl.engine.AbstractCamelContext   :     Started to-rabbitmq-route (direct://serviceJ)
2023-06-27 14:38:53.937  INFO 1 --- [           main] o.a.c.impl.engine.AbstractCamelContext   :     Started fancyService-route (seda://fancy-service)
2023-06-27 14:38:53.937  INFO 1 --- [           main] o.a.c.impl.engine.AbstractCamelContext   : Apache Camel 3.19.0 (camel-1) started in 2s638ms (build:980ms init:1s5ms start:653ms)
2023-06-27 14:38:53.947  INFO 1 --- [           main] g.v.vro.camel.CamelDtoClassesProperties  : Loading classes specified in vro.camel.dto-classes: []
2023-06-27 14:38:53.989  INFO 1 --- [           main] gov.va.vro.camel.CamelConfiguration      : Registering CamelDtoConverter for: class gov.va.vro.model.xample.SomeDtoModel
2023-06-27 14:38:53.990  INFO 1 --- [           main] gov.va.vro.camel.CamelConfiguration      : Registering CamelDtoConverter for: class gov.va.vro.model.xample.StatusValue
2023-06-27 14:38:53.990  INFO 1 --- [           main] gov.va.vro.camel.CamelConfiguration      : Registering CamelDtoConverter for: class gov.va.vro.model.xample.CamelConstants
2023-06-27 14:38:53.999  INFO 1 --- [           main] gov.va.vro.camel.CamelConfiguration      : 7 endpoints:
	- seda://fancy-service -- IfReplyExpected, InOnly, seda://fancy-service?exchangePattern=InOnly
	- direct://no-where -- direct://no-where
	- direct://saveToDb -- direct://saveToDb
	- direct://serviceJ -- direct://serviceJ
	- rabbitmq://v3 -- rabbitmq://v3?queue=postResource&routingKey=postResource
	- direct://serviceA -- direct://serviceA
	- rabbitmq://xample -- rabbitmq://xample?routingKey=serviceJ&skipQueueBind=true
2023-06-27 14:38:54.000  INFO 1 --- [           main] gov.va.vro.camel.CamelConfiguration      : Application started
=====================================
2023-06-27 14:38:54.003  INFO 1 --- [           main] g.v.v.r.x.XampleWorkflowsApplication     : Started XampleWorkflowsApplication in 41.618 seconds (JVM running for 45.859)
2023-06-27 14:39:08.421  INFO 1 --- [io-10021-exec-1] o.a.c.c.C.[Tomcat-1].[localhost].[/]     : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-06-27 14:39:08.422  INFO 1 --- [io-10021-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-06-27 14:39:08.424  INFO 1 --- [io-10021-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
2023-06-27 14:53:21.231  INFO 1 --- [- rabbitmq://v3] postXResource-route                      : Received {CamelRabbitmqCorrelationId=Camel-B66467014B6C992-0000000000000000, CamelRabbitmqDeliveryTag=1, CamelRabbitmqExchangeName=v3, CamelRabbitmqRedeliveryTag=false, CamelRabbitmqReplyTo=amq.gen-PkZSJEdtePd1XGFAWhWIYA, CamelRabbitmqRoutingKey=postResource} class [B: {"resourceId":"123","diagnosticCode":"J","status":null,"statusCode":0,"statusMessage":null}
2023-06-27 14:53:21.396  INFO 1 --- [- rabbitmq://v3] postXResource-route                      : Converted to class gov.va.vro.model.xample.SomeDtoModel: SomeDtoModel(resourceId=123, diagnosticCode=J, status=null, statusCode=0, statusMessage=null)
2023-06-27 14:53:21.407  INFO 1 --- [- rabbitmq://v3] route1                                   : Saving to DB is disabled since the DB schema has been reset after RRD removal
2023-06-27 14:53:21.477  INFO 1 --- [- rabbitmq://v3] postXResource-route                      : After saveToDb, InOut: body class gov.va.vro.model.xample.SomeDtoModel: SomeDtoModel(resourceId=123, diagnosticCode=J, status=RECEIVED, statusCode=0, statusMessage=null)
2023-06-27 14:53:21.483  INFO 1 --- [- rabbitmq://v3] postXResource-route                      : InOut: {CamelRabbitmqCorrelationId=Camel-B66467014B6C992-0000000000000000, CamelRabbitmqDeliveryTag=1, CamelRabbitmqExchangeName=v3, CamelRabbitmqRedeliveryTag=false, CamelRabbitmqReplyTo=amq.gen-PkZSJEdtePd1XGFAWhWIYA, CamelRabbitmqRoutingKey=postResource} Returning to caller: class gov.va.vro.model.xample.SomeDtoModel
2023-06-27 14:53:21.483  INFO 1 --- [//fancy-service] fancyService-route                       : InOnly: {CamelRabbitmqCorrelationId=Camel-B66467014B6C992-0000000000000000, CamelRabbitmqDeliveryTag=1, CamelRabbitmqExchangeName=v3, CamelRabbitmqRedeliveryTag=false, CamelRabbitmqReplyTo=amq.gen-PkZSJEdtePd1XGFAWhWIYA, CamelRabbitmqRoutingKey=postResource} Sending to background service: class gov.va.vro.model.xample.SomeDtoModel
2023-06-27 14:53:22.863  INFO 1 --- [Checker[xample]] fancyService-route                       : Response from service: class gov.va.vro.model.xample.SomeDtoModel: SomeDtoModel(resourceId=123, diagnosticCode=J, status=DONE, statusCode=200, statusMessage=null)
```

```
❯ docker logs vro-svc-xample-j-1
Setting environment variables from VRO_SECRETS_*
Running svc-xample-j-3.1.1-SNAPSHOT.jar; health check port: 10011

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.7.12)

2023-06-27 14:38:14.204  INFO 1 --- [           main] g.v.v.s.x.JavaMicroserviceApplication    : Starting JavaMicroserviceApplication using Java 17.0.7 on da334c985413 with PID 1 (/app/fat.jar started by tron in /app)
2023-06-27 14:38:14.218  INFO 1 --- [           main] g.v.v.s.x.JavaMicroserviceApplication    : No active profile set, falling back to 1 default profile: "default"
2023-06-27 14:38:21.970  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2023-06-27 14:38:22.080  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-06-27 14:38:22.082  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.75]
2023-06-27 14:38:22.438  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-06-27 14:38:22.439  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 7973 ms
2023-06-27 14:38:27.877  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2023-06-27 14:38:28.417  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 10011 (http)
2023-06-27 14:38:28.421  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-06-27 14:38:28.422  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.75]
2023-06-27 14:38:28.428  INFO 1 --- [           main] o.a.c.c.C.[Tomcat-1].[localhost].[/]     : Initializing Spring embedded WebApplicationContext
2023-06-27 14:38:28.429  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 472 ms
2023-06-27 14:38:28.531  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2023-06-27 14:38:29.055  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 10011 (http) with context path ''
2023-06-27 14:38:29.090  INFO 1 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: [rabbitmq-service:5672]
2023-06-27 14:38:29.737  INFO 1 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Created new connection: rabbitConnectionFactory#2baa8d82:0/SimpleConnection@6aa648b9 [delegate=amqp://guest@172.18.0.3:5672/, localPort= 34280]
2023-06-27 14:38:29.770  INFO 1 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable or auto-delete Exchange (xample) durable:true, auto-delete:true. It will be deleted by the broker if it shuts down, and can be redeclared by closing and reopening the connection.
2023-06-27 14:38:29.771  INFO 1 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable, auto-delete, or exclusive Queue (serviceJ) durable:true, auto-delete:true, exclusive:false. It will be redeclared if the broker stops and is restarted while the connection factory is alive, but all messages will be lost.
2023-06-27 14:38:30.383  INFO 1 --- [           main] g.v.v.s.x.JavaMicroserviceApplication    : Started JavaMicroserviceApplication in 18.431 seconds (JVM running for 22.372)
2023-06-27 14:38:38.215  INFO 1 --- [io-10011-exec-1] o.a.c.c.C.[Tomcat-1].[localhost].[/]     : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-06-27 14:38:38.218  INFO 1 --- [io-10011-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-06-27 14:38:38.222  INFO 1 --- [io-10011-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
2023-06-27 14:53:21.797  INFO 1 --- [ntContainer#0-1] g.v.v.s.xample.XampleJavaMicroservice    : Received: SomeDtoModel(resourceId=123, diagnosticCode=J, status=PROCESSING, statusCode=0, statusMessage=null)
```

**Comment by engineer-plus-plus** [comment]
_"To manually test svc-xample-j . . .  go to the POST ​/v3​/xample-resource"_ 

Now I'm really confused.  Please clarify why you propose to use HTTP to test the service whose API is to be exposed through RMQ?

**Comment by yoomlam** [comment]
> _"To manually test svc-xample-j . . . go to the POST ​/v3​/xample-resource"_
> 
> Now I'm really confused. Please clarify why you propose to use HTTP to test the service whose API is to be exposed through RMQ?

Refer to https://github.com/department-of-veterans-affairs/abd-vro/wiki/Software-Conventions

* An HTTP API endpoint is added by:
   - https://github.com/department-of-veterans-affairs/abd-vro/blob/39a1d2ef921d05ad93132487fb487a5b597a3947/domain-xample/xample-api-controller/src/main/java/gov/va/vro/controller/xample/v3/XampleController.java#L31-L32
* The controller sends a MQ message to the Xample Workflow: 
   - https://github.com/department-of-veterans-affairs/abd-vro/blob/39a1d2ef921d05ad93132487fb487a5b597a3947/domain-xample/xample-api-controller/src/main/java/gov/va/vro/controller/xample/v3/XampleController.java#L40
* The Xample Workflow uses Camel to route a MQ message to the `svc-xample-j` microservice:
   - https://github.com/department-of-veterans-affairs/abd-vro/blob/0cafef12934b119996d9c0bad1a9e9b9363c6ffb/domain-xample/xample-workflows/src/main/java/gov/va/vro/routes/xample/XampleRoutes.java#L158-L162

**Comment by engineer-plus-plus** [comment]
😲

**Comment by engineer-plus-plus** [comment]
In any case

1) I should be able to test only the component I'm working on
2) Following these instructions fails when attempting to load the swagger UI:

```
 ilya_standard@ilyaAgile6Mac  ~/Theta/abd-vro  ⇅ develop  source scripts/setenv.sh
./gradlew :dockerComposeUp
./gradlew :domain-xample:dockerComposeUp
COMPOSE_PROFILES="" ./gradlew :app:dockerComposeUp
Using secrets in /Users/ilya_standard/Theta/abd-vro-dev-secrets/local
Setting up environment variables for VRO local development and testing
Not overriding: COMPOSE_PROFILES already set to: 'assessors,feat-toggle,pdf-gen'
Not overriding: SLACK_EXCEPTION_WEBHOOK already set.
Not overriding: LH_ACCESS_CLIENT_ID already set.
Not overriding: LH_PRIVATE_KEY already set.
Not overriding: MAS_API_AUTH_CLIENT_SECRET already set.

> Task :gradle-plugins:initializeIntelliJPlugin
[gradle-intellij-plugin :initializeIntelliJPlugin] Gradle IntelliJ Plugin is outdated: 1.14.1. Update `org.jetbrains.intellij` to: 1.14.2

> Task :dockerComposeUp
time="2023-06-27T15:07:04-06:00" level=warning msg="The \"LH_API_AUTH_URL\" variable is not set. Defaulting to a blank string."
time="2023-06-27T15:07:04-06:00" level=warning msg="The \"VRO_AUD_URL\" variable is not set. Defaulting to a blank string."
time="2023-06-27T15:07:04-06:00" level=warning msg="The \"LH_VRO_API_KEY\" variable is not set. Defaulting to a blank string."
time="2023-06-27T15:07:04-06:00" level=warning msg="The \"VRO_DOCKER_IMAGE_PLATFORM\" variable is not set. Defaulting to a blank string."
time="2023-06-27T15:07:04-06:00" level=warning msg="The \"VRO_DOCKER_IMAGE_PLATFORM\" variable is not set. Defaulting to a blank string."
time="2023-06-27T15:07:04-06:00" level=warning msg="The \"VRO_DOCKER_IMAGE_PLATFORM\" variable is not set. Defaulting to a blank string."
 Container vro-postgres-service-1  Creating
 Container vro-redis-service-1  Creating
 Container vro-rabbitmq-service-1  Creating
 Container vro-postgres-service-1  Created
 Container vro-db-init-1  Creating
 Container vro-rabbitmq-service-1  Created
 Container vro-redis-service-1  Created
 Container vro-db-init-1  Created
 Container vro-rabbitmq-service-1  Starting
 Container vro-postgres-service-1  Starting
 Container vro-redis-service-1  Starting
 Container vro-redis-service-1  Started
 Container vro-postgres-service-1  Started
 Container vro-postgres-service-1  Waiting
 Container vro-rabbitmq-service-1  Started
 Container vro-postgres-service-1  Healthy
 Container vro-db-init-1  Starting
 Container vro-db-init-1  Started

BUILD SUCCESSFUL in 13s
13 actionable tasks: 5 executed, 8 up-to-date

> Task :gradle-plugins:initializeIntelliJPlugin
[gradle-intellij-plugin :initializeIntelliJPlugin] Gradle IntelliJ Plugin is outdated: 1.14.1. Update `org.jetbrains.intellij` to: 1.14.2

> Task :domain-xample:dockerComposeUp
time="2023-06-27T15:07:18-06:00" level=warning msg="Found orphan containers ([vro-db-init-1 vro-postgres-service-1 vro-redis-service-1 vro-rabbitmq-service-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
 Container vro-svc-xample-j-1  Creating
 Container vro-xample-workflows-1  Creating
 Container vro-svc-xample-j-1  Created
 Container vro-xample-workflows-1  Created
 Container vro-svc-xample-j-1  Starting
 Container vro-xample-workflows-1  Starting
 Container vro-xample-workflows-1  Started
 Container vro-svc-xample-j-1  Started

BUILD SUCCESSFUL in 2s
13 actionable tasks: 5 executed, 8 up-to-date

> Task :gradle-plugins:initializeIntelliJPlugin
[gradle-intellij-plugin :initializeIntelliJPlugin] Gradle IntelliJ Plugin is outdated: 1.14.1. Update `org.jetbrains.intellij` to: 1.14.2

> Task :app:dockerComposeUp
time="2023-06-27T15:07:20-06:00" level=warning msg="The \"VRO_AUD_URL\" variable is not set. Defaulting to a blank string."
time="2023-06-27T15:07:20-06:00" level=warning msg="The \"LH_VRO_API_KEY\" variable is not set. Defaulting to a blank string."
time="2023-06-27T15:07:20-06:00" level=warning msg="The \"LH_API_AUTH_URL\" variable is not set. Defaulting to a blank string."
time="2023-06-27T15:07:20-06:00" level=warning msg="The \"LH_VRO_API_KEY\" variable is not set. Defaulting to a blank string."
time="2023-06-27T15:07:20-06:00" level=warning msg="The \"LH_API_AUTH_URL\" variable is not set. Defaulting to a blank string."
time="2023-06-27T15:07:20-06:00" level=warning msg="The \"VRO_AUD_URL\" variable is not set. Defaulting to a blank string."
time="2023-06-27T15:07:20-06:00" level=warning msg="Found orphan containers ([vro-xample-workflows-1 vro-svc-xample-j-1 vro-db-init-1 vro-postgres-service-1 vro-redis-service-1 vro-rabbitmq-service-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up."
 Container vro-app-1  Creating
 Container vro-app-1  Created
 Container vro-app-1  Starting
 Container vro-app-1  Started

BUILD SUCCESSFUL in 1s
13 actionable tasks: 5 executed, 8 up-to-date
 ilya_standard@ilyaAgile6Mac  ~/Theta/abd-vro  ⇅ develop  curl http://localhost:8110/swagger
curl: (52) Empty reply from server
```
